-- DROP USER MBG;

CREATE USER "MBG" IDENTIFIED BY "${APX_PWD}"
      DEFAULT TABLESPACE "SYSAUX"
      TEMPORARY TABLESPACE "TEMP";

ALTER USER MBG quota unlimited ON SYSAUX;

GRANT CREATE SESSION TO "MBG";
GRANT CREATE TABLE TO "MBG";
GRANT CREATE CLUSTER TO "MBG";
GRANT CREATE SYNONYM TO "MBG";
GRANT CREATE VIEW TO "MBG";
GRANT CREATE SEQUENCE TO "MBG";
GRANT CREATE PROCEDURE TO "MBG";
GRANT CREATE TRIGGER TO "MBG";
GRANT CREATE MATERIALIZED VIEW TO "MBG";
GRANT CREATE TYPE TO "MBG";
GRANT CREATE OPERATOR TO "MBG";
GRANT CREATE INDEXTYPE TO "MBG";
GRANT CREATE DIMENSION TO "MBG";
GRANT CREATE JOB TO "MBG";
GRANT EXECUTE DYNAMIC MLE TO "MBG";

GRANT EXECUTE ON "SYS"."JAVASCRIPT" TO "MBG";